# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 04:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=15)),
                ('kadi_count', models.IntegerField()),
                ('is_lastet', models.BooleanField(default=True)),
                ('save_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeCountRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_count', models.IntegerField()),
                ('real_count', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=15)),
                ('average_price', models.FloatField()),
                ('last_price', models.FloatField()),
                ('update_date', models.DateField(auto_now_add=True)),
                ('recent_sell', models.DateField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('add_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsAddRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('price', models.FloatField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucun.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_num', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucun.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReturnRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsSellRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_num', models.IntegerField()),
                ('average_price', models.FloatField()),
                ('sell_price', models.FloatField()),
                ('is_arrears', models.BooleanField()),
                ('customer', models.CharField(default='无', max_length=10)),
                ('phonenumber', models.CharField(default='无', max_length=15)),
                ('address', models.CharField(default='无', max_length=50)),
                ('remark', models.TextField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucun.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remain', models.IntegerField()),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucun.Goods')),
                ('last_updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InboundChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('phonenumber', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucun.GoodsShop')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_arrears', models.BooleanField()),
                ('customer', models.CharField(default='无', max_length=10)),
                ('phonenumber', models.CharField(default='无', max_length=15)),
                ('address', models.CharField(default='无', max_length=50)),
                ('remark', models.TextField(blank=True, null=True)),
                ('all_price', models.FloatField(default=0)),
                ('all_profit', models.FloatField(default=0)),
                ('is_delete', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtherCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('is_delete', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sell_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucun.GoodsSellRecord')),
                ('updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('remark', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucun.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='TransferShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='transfer_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucun.TransferShop'),
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsshop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucun.Shop'),
        ),
        migrations.AddField(
            model_name='goodssellrecord',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kucun.Order'),
        ),
        migrations.AddField(
            model_name='goodssellrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucun.Shop'),
        ),
        migrations.AddField(
            model_name='goodssellrecord',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreturnrecord',
            name='goods_sell_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucun.GoodsSellRecord'),
        ),
        migrations.AddField(
            model_name='goodsreturnrecord',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucun.Shop'),
        ),
        migrations.AddField(
            model_name='goodsrecord',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsaddrecord',
            name='inbound_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucun.InboundChannel'),
        ),
        migrations.AddField(
            model_name='goodsaddrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucun.Shop'),
        ),
        migrations.AddField(
            model_name='goodsaddrecord',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changecountrecord',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kucun.Goods'),
        ),
        migrations.AddField(
            model_name='changecountrecord',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
